// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJcCy339UNX3DMWZwcx0mec8ayFlV19iI',
    appId: '1:601726379652:web:78b3aab0e67e095f80c4d1',
    messagingSenderId: '601726379652',
    projectId: 'lol-matching',
    authDomain: 'lol-matching.firebaseapp.com',
    storageBucket: 'lol-matching.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4OF7iK9hoGSHX4TmWuR-sTXZRrWddFw',
    appId: '1:601726379652:android:e11633fba1c7d16d80c4d1',
    messagingSenderId: '601726379652',
    projectId: 'lol-matching',
    storageBucket: 'lol-matching.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkRd1fip-oZ2V0Q86knMpeJ33zFkhtRhk',
    appId: '1:601726379652:ios:0860980eadcabe4880c4d1',
    messagingSenderId: '601726379652',
    projectId: 'lol-matching',
    storageBucket: 'lol-matching.appspot.com',
    iosClientId: '601726379652-vnrkulfa51oqa9rd75efvjt6saknqjpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.lolMatching',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkRd1fip-oZ2V0Q86knMpeJ33zFkhtRhk',
    appId: '1:601726379652:ios:0860980eadcabe4880c4d1',
    messagingSenderId: '601726379652',
    projectId: 'lol-matching',
    storageBucket: 'lol-matching.appspot.com',
    iosClientId: '601726379652-vnrkulfa51oqa9rd75efvjt6saknqjpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.lolMatching',
  );
}
